export const bookData5 = [
    {
        id: "ch26", chapterNum: "26", title: "WHAT DOES ISLAM SAY ABOUT HUMANITY?",
        sections: [
            { subtitle: "26.1 All humans share the same origin", content: "", verses: [{ text: "O mankind! Be conscious of your Guardian-Lord, who created you from a single person, created, of like nature, his mate, and from these two scattered (like seeds) many men and women; Be conscious of Allah, through whom you demand your mutual (rights), and of family ties: for Allah ever watches over you.", reference: "Ch 4: V 1" }] },
            { subtitle: "26.2 Differences in skin colour and languages are signs of Allah", content: "", verses: [{ text: "And among His Signs is the creation of the heavens and the earth, and the variations in your languages and your colours: Verily in that are Signs for those who know.", reference: "Ch 30: V22" }] },
            { subtitle: "26.3 Purpose of differences is to know and learn from one another", content: "", verses: [{ text: "O mankind! We created you from a single (pair) of a male and a female, and made you into nations and tribes, that you may know each other (not that you may despise each other). Verily the most honoured of you in the sight of Allah is (he who is) the most righteous of you. And Allah has full knowledge and is well acquainted (with all things).", reference: "Ch 49: V13" }] },
            { subtitle: "26.4 Mankind is one – divisions are caused by selfishness and jealousy", content: "", verses: [{ text: "Mankind was one single nation, and Allah sent Messengers with glad tidings and warnings; and with them He sent the Book in truth, to judge between people in matters wherein they differed; but the People of the Book, after the Clear Signs came to them, did not differ among themselves, except through mutual jealousy. Allah by His Grace guided the believers to the truth, concerning that wherein they differed. For Allah guided whom He will to a path that is straight.", reference: "Ch 2: V 213" }] }
        ]
    },
    {
        id: "ch27", chapterNum: "27", title: "DOES ISLAM PERMIT FIGHTING?",
        sections: [
            { subtitle: "27.1 Jihad and Qitaal", content: "Quite often, people use the word Jihad to describe warfare in Islam. This according to the Quran is not correct. Whereas the word describing warfare in the Quran is Qitaal or Harb, the word Jihad, in the Quran, refers to utilising one’s energy to the utmost. For example the Quran says:", verses: [{ text: "Therefore listen not to the unbelievers, but strive against them with total commitment, with the (Quran).", reference: "Ch 25: V52" }] },
            { subtitle: "27.2 Qitaal or Fighting (in the cause of God)", content: "", verses: [] },
            { subtitle: "27.2.1 Conditions under which believers are permitted to fight", content: "", verses: [{ text: "To those against whom war is made, permission is given (to fight), because they are wronged; and verily, Allah is Most powerful for their help.", reference: "Ch 22: V39" }, { text: "And why should you not fight in the cause of Allah and of those who, being weak, are ill-treated (and oppressed)? Men, women, and children, whose cry is: “Our Lord! Rescue us from this town, whose people are oppressors; and raise for us from You one who will protect; and raise for us from You one who will help!”", reference: "Ch 4: V 75" }, { text: "But if they violate their oaths after their covenant, and taunt you for your faith, fight you the chiefs of unfaith: for their oaths are nothing to them: that thus they may be restrained.", reference: "Ch 9: V12" }] },
            { subtitle: "27.2.2 Believers must not to be the aggressors:", content: "", verses: [{ text: "Fight in the cause of Allah those who fight you, but do not transgress limits; for Allah loves not transgressors.", reference: "Ch 2: V 190" }] },
            { subtitle: "27.2.3 Believers not to turn back once engaged in battle:", content: "", verses: [{ text: "O you who believe! When you meet the unbelievers in battle, never turn your backs to them. If any do turn his back to them on such a day - unless it be in a strategy of war, or to retreat to a troop (of his own)- he draws on himself the wrath of Allah, and his abode is Hell – an evil refuge (indeed).", reference: "Ch 8: V15 - 16" }] },
            { subtitle: "27.2.4 Believers to be well armed and prepared", content: "", verses: [{ text: "Against them make ready your strength to the utmost of your power, including steeds of war, to strike terror into (the hearts of) the enemies of Allah and your enemies, and others besides, whom you may not know, but whom Allah does know.", reference: "Ch 8: V60" }, { text: "... and We sent down iron, in which is (material for) mighty war, as well as many benefits for mankind…", reference: "Ch 57: V25" }] },
            { subtitle: "27.2.5 Encouraged to fight in legitimate warfare", content: "", verses: [{ text: "Allah has purchased of the believers their persons and their goods; for theirs (in return) is the garden (of Paradise): they fight in His cause, and kill and are killed: a promise binding on Him in truth, through the Law, the Gospel, and the Quran: and who is more faithful to his covenant than Allah? Then rejoice in the bargain which ye have concluded: that is the achievement supreme.", reference: "Ch 9: V111" }] },
            { subtitle: "27.2.6 To accept peace unless suspicion of treachery", content: "", verses: [{ text: "But if the enemy incline towards peace, do you (also) incline towards peace, and trust in Allah: for He is One that hears and knows (all things).", reference: "Ch 8: V61" }, { text: "If you fear treachery from any group, throw back (their covenant) to them, (so as to be) on equal terms: for Allah loves not the treacherous.", reference: "Ch 8: V58" }] },
            { subtitle: "27.2.7 Prisoners of war to be released once the war ends", content: "", verses: [{ text: "Therefore, when you meet the unbelievers (in fight), strike at their necks; At length, when you have thoroughly subdued them, bind a bond firmly (on them): thereafter (is the time for) either generosity or ransom: until the war is over.", reference: "Ch 47: V4" }] }
        ]
    },
    {
        id: "ch28", chapterNum: "28", title: "WHAT DOES ALLAH SAY ABOUT KNOWLEDGE?",
        sections: [
            { subtitle: "28.1 Reading & writing are teachings of Allah", content: "", verses: [{ text: "Read! In the name of your Lord and Cherisher, Who created-\ncreated man, out of a (mere) clot of congealed blood:\nRead! And your Lord is Most Bountiful,-\nHe who taught (the use of) the pen,-\nTaught man that which he knew not.", reference: "Ch 96: V1-5" }] },
            { subtitle: "28.2 Educating one’s self is important", content: "", verses: [{ text: "…Say: “Are those equal, those who know and those who do not know? It is those who are endued with understanding that receive admonition.", reference: "Ch 39: V9" }] },
            { subtitle: "28.3 Requires opening one’s heart and mind", content: "", verses: [{ text: "Do they not then earnestly seek to understand the Quran, or are there locks on their hearts?", reference: "Ch 47: V24" }] },
            { subtitle: "28.4 To be a believer one must study the Quran", content: "", verses: [{ text: "Those to whom we have sent the Book study it as it should be studied: they are the ones that believe therein: those who reject faith therein,- the loss is their own.", reference: "Ch 2: V 121" }] },
            { subtitle: "28.5 Studying and teaching is highly regarded", content: "", verses: [{ text: "Nor should the believers all go forth together (in fighting): if a group from every expedition remained behind, they could devote themselves to studies in religion, and warn the people when they return to them, that thus they (may learn) to guard themselves (against evil).", reference: "Ch 9: V122" }] },
            { subtitle: "28.6 A knowledgeable person is one who stands in awe of Allah", content: "", verses: [{ text: "... those truly fear Allah, among His servants, who have knowledge: for Allah is Exalted in Might, Oft-Forgiving.", reference: "Ch 35: V28" }] },
            { subtitle: "28.7 Knowledge must be translated into action", content: "", verses: [{ text: "The example of those who were entrusted with the (obligations of the) Torah, and did not apply it in their daily lives, is that of a donkey which carries huge books. Evil is the example of people who deny Allah’s verses by their action. Allah does not show the way to people who displace revelation from its rightful station.", reference: "Ch 62: V5" }] },
            { subtitle: "28.8 The servants of Allah study creation", content: "", verses: [{ text: "Behold! In the creation of the heavens and the earth, and the alternation of night and day, there are indeed signs for men of understanding,\nMen who celebrate the praises of Allah, standing, sitting, and lying down on their sides, and contemplate the (wonders of) creation in the heavens and the earth, (with the thought): “Our Lord! Not for nothing have You created (all) this! Glory to You! Save us from the penalty of the Fire.", reference: "Ch 3: V190 - 191" }] },
            { subtitle: "28.9 Allah’s signs are found in the natural phenomena around us", content: "", verses: [{ text: "On the earth are signs for those who have certainty of faith, as also in your own selves: will you not then see?", reference: "Ch 51: V20 - 21" }] },
            { subtitle: "28.10 Geology is among Allah’s signs", content: "", verses: [{ text: "Do you not see that Allah sends down rain from the sky? With it We then bring out produce of various colours and in the mountains are tracts white and red, of various shades of colour, and black intense in hue.", reference: "Ch 35: V27" }] },
            { subtitle: "28.11 Biology is among Allah’s signs", content: "", verses: [{ text: "O mankind! If you have a doubt about the Resurrection, (consider) that We created you out of dust, then out of sperm, then out of a leech-like clot, then out of a morsel of flesh, partly formed and partly unformed, in order that We may show (Our power) to you; and We cause whom We will to rest in the wombs for an appointed term, then do We bring you out as babies, then (foster you) that you may reach your age of full strength; and some of you are called to die, and some are sent back to the feeblest old age, so that they know nothing after having known (much), and (further), you see the earth barren and lifeless, but when we pour down rain on it, it is stirred (to life), it swells, and it puts forth every kind of beautiful growth (in pairs).", reference: "Ch 22: V5" }] },
            { subtitle: "28.12 History is among Allah’s signs", content: "", verses: [{ text: "Do they not travel through the earth, and see what was the end of those before them (who did evil)? Allah brought utter destruction on them, and similar (fate await) those who reject Allah.", reference: "Ch 47: V10" }] }
        ]
    },
    {
        id: "ch29", chapterNum: "29", title: "WHAT DOES ALLAH SAY ABOUT WOMEN?",
        sections: [
            { subtitle: "29.1 Men and women are equal in the sight of Allah", content: "", verses: [{ text: "For Muslim men and women,- for believing men and women, for devout men and women, for true men and women, for men and women who are patient and constant, for men and women who humble themselves, for men and women who give in charity, for men and women who fast (and deny themselves), for men and women who guard their chastity, and for men and women who engage much in Allah’s praise,- for them has Allah prepared forgiveness and great reward.", reference: "Ch 33: V35" }, { text: "The believers, men and women, are protectors one of another: they enjoin what is just, and forbid what is evil: they observe regular prayers, practise regular charity, and obey Allah and His Messenger. On them will Allah pour His Mercy: for Allah is Exalted in Power, Wise.", reference: "Ch 9: V71" }] },
            { subtitle: "29.2 Special rules of dressing for women", content: "", verses: [{ text: "And say to the believing women that they should lower their gaze and guard their modesty; that they should not display their beauty and ornaments except what (must ordinarily) appear thereof; that they should draw their veils over their bosoms and not display their beauty except to their husbands, their fathers, their husband’s fathers, their sons, their husbands’ sons, their brothers or their brothers’ sons, or their sisters’ sons, or their women, or those under their custody, or male servants free of physical needs, or small children who have no sense of the shame of sex; and that they should not strike their feet in order to draw attention to their hidden ornaments. And O you believers! Turn ye all together towards Allah, that ye may attain success.", reference: "Ch 24: V 31" }] },
            { subtitle: "29.3 Should cover themselves when going out", content: "", verses: [{ text: "O Prophet! Tell your wives and daughters, and the believing women, that they should cast their outer garments over their persons (when outdoors): that is most convenient, that they should be known (as such) and not harmed and Allah is Oft- Forgiving, Most Merciful.", reference: "Ch 33: V59" }] },
            { subtitle: "29.4 Right to Inheritance", content: "", verses: [{ text: "From what is left by parents and those nearest related there is a share for men and a share for women, whether the property be small or large, a determinate share.", reference: "Ch 4: V 7" }] },
            { subtitle: "29.5 Right to dowry when married", content: "", verses: [{ text: "And give the women (on marriage) their dower as a free gift; but if they, of their own good pleasure, remit any part of it to you, take it and enjoy it with good cheer.", reference: "Ch 4: V 4" }] },
            { subtitle: "29.6 Right to protect herself in marriage", content: "", verses: [{ text: "If a wife fears cruelty or desertion on her husband’s part, there is no blame on them if they arrange an amicable settlement between themselves; and such settlement is best; even though men’s souls are swayed by greed. But if you do good and practise self-restraint, Allah is well-acquainted with all that you do.", reference: "Ch 4: V 128" }] },
            { subtitle: "29.7 Right to maintenance if divorced", content: "", verses: [{ text: "For divorced women maintenance (should be provided) on a reasonable (scale). This is a duty on the righteous.", reference: "Ch 2: V 241" }] },
            { subtitle: "29.8 Have an equal reward for their actions", content: "", verses: [{ text: "And their Lord has accepted of them, and answered them: “Never will I lose sight of the work of any of you, male or female: you are members, one of another: those who have left their homes, or been driven out there from, or suffered harm in My cause, or fought or been killed,- Verily, I will blot out from them their sins, and admit them into Gardens with rivers flowing beneath;- a reward from the presence of Allah, and from His presence is the best of rewards.”", reference: "Ch 3: V195" }] }
        ]
    },
    {
        id: "ch30", chapterNum: "30", title: "WHAT DOES ALLAH SAY ABOUT SATAN?",
        sections: [
            { subtitle: "30.1 He is our enemy", content: "", verses: [{ text: "Verily Satan is an enemy to you: so treat him as an enemy. He only invites his followers that they may become companions of the blazing fire.", reference: "Ch 35: V6" }] },
            { subtitle: "30.2 Satan waiting on the straight path trying to divert those on it", content: "", verses: [{ text: "(Satan said:)...Lo! I will lie in wait for them on your straight way.", reference: "Ch 7: V16" }] },
            { subtitle: "30.3 Can only suggests ideas to you", content: "", verses: [{ text: "And Satan will say when the matter is decided: It was Allah who gave you a promise of truth: I too promised, but I failed in my promise to you. I had no authority over you except to call you but you listened to me: then do not blame me, but blame your own souls. I cannot listen to your cries, nor can you listen to mine. I reject your former act in associating me with Allah. For wrong-doers there must be a grievous penalty.", reference: "Ch 14: V22" }] },
            { subtitle: "30.4 Causes division among people", content: "", verses: [{ text: "Say to My servants that they should (only) say those things that are best: for Satan does create divisions among them: for Satan is to man an open enemy.", reference: "Ch 17: V53" }] },
            { subtitle: "30.5 Makes false promises", content: "", verses: [{ text: "Satan makes them promises, and creates in them false desires; but Satan’s promises are nothing but deception.", reference: "Ch 4: V 120" }] },
            { subtitle: "30.6 Commands what is shameful", content: "", verses: [{ text: "O you who believe! follow not Satan’s footsteps: if any will follow the footsteps of Satan, he will (but) command what is shameful and wrong: and were it not for the Grace and Mercy of Allah on you, not one of you would ever have been pure: but Allah does purify whom He pleases: and Allah is One who hears and knows (all things).", reference: "Ch 24: V 21" }] },
            { subtitle: "30.7 Our companion if we do not remember Allah", content: "", verses: [{ text: "If anyone withdraws himself from remembrance of (Allah) Most Gracious, We appoint for him a satan, to be an intimate companion to him.", reference: "Ch 43: V36" }] },
            { subtitle: "30.8 Allah protects us from Satan", content: "", verses: [{ text: "If a suggestion from Satan enters your (mind), seek refuge with Allah, for He hears and knows (all things). Those who fear Allah, when a thought of evil from Satan is suggested to them, bring Allah to remembrance, when lo! They see (aright)!", reference: "Ch 7: V200 - 201" }] }
        ]
    },
    {
        id: "ch31", chapterNum: "31", title: "SINS AND REPENTANCE",
        sections: [
            { subtitle: "31.1 Allah is the granter of forgiveness", content: "", verses: [{ text: "He is the One that accepts repentance from His servants and forgives sins: and He knows all that you do.", reference: "Ch 42: V 25" }] },
            { subtitle: "31.2 Never despair of Allah’s mercy", content: "", verses: [{ text: "Say: “O My servants who have transgressed against their souls! Despair not of the Mercy of Allah, for Allah forgives all sins: for He is Oft-Forgiving, Most Merciful”.", reference: "Ch 39: V53" }] },
            { subtitle: "31.3 Associating others with Allah is unforgivable unless one amends", content: "", verses: [{ text: "Allah forgives not that partners should be set up with Him; but He forgives anything else, to whom He please; to set up partners with Allah is to devise a great sin indeed.", reference: "Ch 4: V 48" }] },
            { subtitle: "31.4 Sins in ignorance", content: "", verses: [{ text: "When those come to you who believe in our signs, say: “Peace be on you: your Lord has inscribed for Himself (the rule of) mercy: Verily, if any of you did evil in ignorance, and thereafter repented, and amended (his conduct), Lo! He is Oft- Forgiving, Most Merciful.", reference: "Ch 6: V54" }] },
            { subtitle: "31.5 Never repeat the same sin", content: "", verses: [{ text: "And those who, having done something to be ashamed of, or wronged their own souls, earnestly bring Allah to mind, and ask for forgiveness for their sins,- and who can forgive sins except Allah? – And they never persist knowingly in (the wrong) they have done.", reference: "Ch 3: V135" }] },
            { subtitle: "31.6 Change of behaviour is counted as true repentance", content: "", verses: [{ text: "Unless he repents, believes, and works righteous actions, for Allah will change the evil of such persons into good, and Allah is Oft-Forgiving, Most Merciful,\nAnd whoever repents and does good has truly turned to Allah with true repentance.", reference: "Ch 25: V70 - 71" }] }
        ]
    },
    {
        id: "conclusion", chapterNum: "Conclusion", title: "CONCLUSION",
        sections: [
            { subtitle: "Pathway to light", content: "The final message from Allah – the Quran – is for people from all walks of life, inviting to the pathway of light. Let us begin this journey to the light of revelation and thus achieve true peace and success in both this world and the next.", verses: [] },
            { subtitle: "The Beginning; not the End", content: "The content of this book provides a basic starting point and we ask the reader to begin the journey of enlightenment by reading and understanding the Quran in its entirety.", verses: [] },
            { subtitle: "Allah Answers", content: "Life is full of choices that can be challenging, however the All-Knowing (Allah) answers. Our duty is to open the Quran for guidance in all states, whether happy or sad, celebrating or grieving, stressed or relaxed.", verses: [] },
            { subtitle: "Prayer", content: "We pray that Allah gives us the will to say “no” to disunity and unite us under the final message of Allah. May He give us the strength to live up to the standards set by the Prophets in purifying the world and making it a better one for us and future generations. May Allah bless and guide you on this pathway to light and shower you with His mercy. We pray that He forgives our shortcomings and mistakes we may have made and bring us closer to Him.", verses: [] },
            { subtitle: "REMEMBER: The 5 duties we owe to the Quran (Believe & RUn For iT)", content: "► Believe in it\n► Read it (at least daily)\n► UNderstand it (by reading it in a language we understand)\n► Follow it and\n► Teach it (to others).", verses: [] }
        ]
    }
];
