export const bookData2 = [
  {
    id: "ch8", chapterNum: "8", title: "WHAT ARE THE COMMON PRACTICES OF ISLAM?",
    sections: [
      { subtitle: "", content: "To testify that there is none worthy of worship besides Allah, to perform regular prayer, to give regular charity, to fast in the month of Ramadan and to perform the pilgrimage to Mecca once in a lifetime if affordable and able.", verses: [] },
      { subtitle: "8.1 Belief in One God", content: "", verses: [{ text: "And they have been commanded no more than this: To worship Allah, offering Him sincere devotion, being true (in faith); ... and that is the Religion Right and Straight.", reference: "Ch 98: V5" }] },
      { subtitle: "8.2 Salah (Prayer)", content: "", verses: [] },
      { subtitle: "8.2.1 Purpose: for the remembrance of Allah", content: "", verses: [{ text: "(Allah said): “There is no god but I: So serve Me (only), and establish regular prayer for My remembrance.”", reference: "Ch 20: V14" }] },
      { subtitle: "8.2.2 At prescribed times", content: "", verses: [{ text: "... But when you are free from danger, set up regular prayers: For such prayers are enjoined on believers at stated times.", reference: "Ch 4: V 103" }] },
      { subtitle: "8.2.3 Preparation for prayer: Ablution", content: "", verses: [{ text: "O you who believe! When you prepare for prayer, wash your faces, and your hands (and arms) to the elbows; rub your heads (with water); and (wash) your feet to the ankles. If you are in a state of ceremonial impurity, bath your whole body. But if you are ill, or on a journey, or one of you comes from the toilet, or you have been in intimate contact with women, and you find no water, then take for yourselves clean sand or earth, and rub therewith your faces and hands, Allah does not wish to place you in difficulty, but to make you clean, and to complete His favour to you, that you may be grateful.", reference: "Ch 5: V7" }] },
      { subtitle: "8.2.4 Need to know (be conscious of) what is said in prayers", content: "", verses: [{ text: "O you who believe! Approach not prayers with an intoxicated mind, until you can understand all that you say...", reference: "Ch 4: V 43" }] },
      { subtitle: "8.2.5 Acts of bowing and prostrating", content: "", verses: [{ text: "... You will see them bow and prostrate themselves (in prayer), seeking Grace from Allah and (His) Good Pleasure...", reference: "Ch 48: V29" }] },
      { subtitle: "8.2.6 Shortening of prayers when in danger", content: "", verses: [{ text: "When you travel through the earth, there is no blame on you if you shorten your prayers, for fear the unbelievers may harass you ...", reference: "Ch 4: V 101" }] },
      { subtitle: "8.3 Zakaah (Charity)", content: "Refer to Economic laws section (24)", verses: [] },
      { subtitle: "8.4 Fasting", content: "", verses: [] },
      { subtitle: "8.4.1 Prescribed", content: "", verses: [{ text: "O you who believe! Fasting is prescribed to you as it was prescribed to those before you, that you may guard against evil.", reference: "Ch 2: V 183" }] },
      { subtitle: "8.4.2 For the complete month of Ramadan", content: "", verses: [{ text: "Ramadan is the (month) ... So every one of you who is present (at his home) during that month should spend it in fasting, but if anyone is ill, or on a journey, the prescribed period (should be made up) by days later. Allah intends ease for you; He does not want to put you to difficulties. (He wants you) to complete the prescribed period, and to glorify Him in that He has guided you; and perchance you shall be grateful.", reference: "Ch 2: V185" }] },
      { subtitle: "8.4.3 Laws relaxed for the night", content: "", verses: [{ text: "Permitted to you, on the night of the fasts, is the approach to your wives. They are your garments and you are their garments. Allah knows what you used to do secretly among yourselves; but He turned to you and forgave you; so now associate with them, and seek what Allah has ordained for you, and eat and drink, until the white thread of dawn appear to you distinct from its black thread; then complete your fast till the night appears; but do not associate with your wives while you are in retreat in the mosques. Those are limits (set by) Allah: approach not near thereto. Thus doth Allah make clear His Signs to men: that they may learn self-restraint.", reference: "Ch 2: V 187" }] },
      { subtitle: "8.5 Hajj (Pilgramage)", content: "", verses: [] },
      { subtitle: "8.5.1 Hajj is a duty owed to Allah if you can afford it", content: "", verses: [{ text: "The first House (of worship) appointed for men was that at Bakka(Mecca): Full of blessing and of guidance for all kinds of beings:\n...Pilgrimage thereto is a duty men owe to Allah, - those who can afford the journey; but if any deny faith, Allah stands not in need of any of His creation.", reference: "Ch 3: V96-97" }] },
      { subtitle: "8.5.2 Holy Mosque in Mecca - political centre", content: "", verses: [{ text: "Allah has appointed the Ka’bah, the Sacred House, as a place of congregation and a centre ...", reference: "Ch 2: V 125" }] },
      { subtitle: "8.5.3 Good behaviour during Hajj", content: "", verses: [{ text: "... Whoever undertakes the journey shall abstain from marital relations, not indulge in ungodliness nor wrangle during the (prescribed days of) Hajj.", reference: "Ch 2: V 197" }] },
      { subtitle: "8.5.4 Comprises sacred rites", content: "", verses: [{ text: "Such (is the pilgrimage): whoever honours the sacred rites of Allah, for him it is good in the sight of his Lord...", reference: "Ch 22: V 30" }] },
      { subtitle: "8.5.5 Arafat and Muzdalifah (Masharil-Haraam)", content: "", verses: [{ text: "... but when you press on in the multitude from ‘Arafat, remember Allah at Masharil Haraam (Muzdalifah). Remember Him as He has guided you, although before you were of those astray,", reference: "Ch 2: V 198" }] },
      { subtitle: "8.5.6 Tawaaf (Circumambulating around the Kaba)", content: "", verses: [{ text: "Then they should complete the prescribed rites, perform their vows and go around the ancient House.", reference: "Ch 22: V 29" }] },
      { subtitle: "8.5.7 Saee – going around Safa and Marwa", content: "", verses: [{ text: "Surely Al-Safa and Al-Marwah are among the Signs of Allah. It is, therefore, no sin for the pilgrim or he who performs Umrah, to make tawaaf (go around) around the two.", reference: "Ch 2: V 158" }] },
      { subtitle: "8.5.8 Sacrifice during Hajj", content: "", verses: [{ text: "……The sacrificial camels We have made for you as among the symbols from Allah …. Eat you thereof and feed the needy ...", reference: "Ch 22: V 36" }] },
      { subtitle: "8.5.9 Uphold the spirit of Hajj on your return home", content: "", verses: [{ text: "And when you have completed your devotions, then remember Allah as you remember your fathers but with far more heart and soul.", reference: "Ch 2: V 200" }] }
    ]
  },
  {
    id: "ch9", chapterNum: "9", title: "WHAT DOES ALLAH SAY ABOUT THE QURAN?",
    sections: [
      { subtitle: "9.1 Cannot be produced by other than Allah", content: "", verses: [{ text: "This Quran is not such as can be produced by anyone other than Allah...", reference: "Ch 10: V37" }] },
      { subtitle: "9.2 Is protected by Allah (from change)", content: "", verses: [{ text: "We have, without doubt, sent down the Message; and We will certainly guard it (from corruption).", reference: "Ch 15: V9" }] },
      { subtitle: "9.3 No discrepancies or contradictions in it", content: "", verses: [{ text: "Do they not consider the Quran (with care)? Had it been from other than Allah, they would surely have found in it much contradiction.", reference: "Ch 4: V 82" }, { text: "Praise be to Allah, Who has sent to His servant the Book, and has allowed therein no crookedness:", reference: "Ch 18: V1" }] },
      { subtitle: "9.4 Easy to understand and remember", content: "", verses: [{ text: "And We have indeed made the Quran easy to understand and remember: then is there any that will receive admonition?", reference: "Ch 54: V17 (also verses 22,32,40)" }] },
      { subtitle: "9.5 Commanded to understand it", content: "", verses: [{ text: "Do they not then earnestly seek to understand the Quran, or are there locks on their hearts?", reference: "Ch 47: V24" }] },
      { subtitle: "9.6 To follow it and not other paths", content: "", verses: [{ text: "Verily this is My (Allah’s) way, leading straight: follow it, follow not (other) paths: they will scatter you about from His (great) path: thus does He command you that you may be righteous.", reference: "Ch 6: V153" }] },
      { subtitle: "9.7 Is a blessing and a mercy if we follow it", content: "", verses: [{ text: "And this is a Book which We have revealed as a blessing: so follow it and be righteous, that you may receive mercy:", reference: "Ch 6: V155" }] },
      { subtitle: "9.8 Clarifies differences", content: "", verses: [{ text: "And We sent down the Book to you for the express purpose, that you should make clear to them those things in which they differ, and that it should be a guide and a mercy to those who believe.", reference: "Ch 16: V64" }] },
      { subtitle: "9.9 Is a criterion", content: "", verses: [{ text: "Blessed is He who sent down the criterion (the Quran a judgement between right and wrong) to His servant, that it may be a warning to all creation.", reference: "Ch 25: V1" }] }
    ]
  },
  {
    id: "ch10", chapterNum: "10", title: "HOW DOES ISLAM VIEW OTHER FAITHS AND THEIR SCRIPTURES?",
    sections: [
      { subtitle: "10.1 Guarantees freedom of religion", content: "", verses: [{ text: "Let there be no compulsion in religion: truth stands out clear from error…", reference: "Ch 2: V 256" }] },
      { subtitle: "10.2 Belief in previous scriptures and Prophets", content: "", verses: [{ text: "Say you: “We believe in Allah, and the revelation given to us, and to Abraham, Ismail, Isaac, Jacob, and the Tribes, and that given to Moses and Jesus, and that given to (all) prophets from their Lord: We make no difference between one and another of them: And we bow to Allah (in Islam).”", reference: "Ch 2: V 136" }] },
      { subtitle: "10.3 The Quran exposes the changes made to the previous scriptures", content: "", verses: [{ text: "O People of the Book! There has come to you Our Messenger, revealing to you much that you used to hide in the Book, and passing over much (that is now unnecessary): there has come to you from Allah a (new) light and a clear Book.", reference: "Ch 5: V16-17" }] },
      { subtitle: "10.4 Calls to common terms with people of other faiths", content: "", verses: [{ text: "Say: “O People of the Book! Come to common terms as between us and you: that we worship none but Allah; that we associate no partners with Him; that we erect not, from among ourselves, Lords and patrons other than Allah.” If then they turn back, say you: “Bear witness that we (at least) are Muslims (bowing to Allah’s Will).", reference: "Ch 3: V64" }] },
      { subtitle: "10.5 Rewarded if they believe in Allah, the last day and do good", content: "", verses: [{ text: "Those who believe (in the Quran), and those who follow the Jewish (scriptures), and the Christians and the Sabians,- any who believe in Allah and the Last Day, and do good, shall have their reward with their Lord; on them shall be no fear, nor shall they grieve.", reference: "Ch 2: V 62" }] },
      { subtitle: "10.6 Warns against going beyond the Truth", content: "", verses: [{ text: "Say: “O people of the Book! exceed not in your religion the bounds (of what is proper), trespassing beyond the truth, nor follow the vain desires of people who went wrong in times gone by,- who misled many, and strayed (themselves) from the even way.", reference: "Ch 5: V80" }] },
      { subtitle: "10.7 Believers to have good relations with other faiths", content: "", verses: [{ text: "Allah forbids you not, with regard to those who fight you not for (your) Faith nor drive you out of your homes, from dealing kindly and justly with them: for Allah loveth those who are just.\n\nAllah only forbids you, with regard to those who fight you for (your) religion, and drive you out of your homes, and support (others) in driving you out, from turning to them (for friendship and protection). It is such as turn to them (in these circumstances), that do wrong.", reference: "Ch 60: V8-9" }] },
      { subtitle: "10.8 Believers to invite people of other faiths with courtesy and wisdom", content: "", verses: [{ text: "Invite (all) to the Way of your Lord with wisdom and beautiful preaching; and argue with them in ways that are best and most gracious: for your Lord knows best, who have strayed from His path, and who receive guidance.", reference: "Ch 16: V125" }] }
    ]
  },
  {
    id: "ch11", chapterNum: "11", title: "WHAT DOES ALLAH SAY ABOUT BLIND FOLLOWING",
    sections: [
      { subtitle: "11.1 Following traditions can be an obstacle to the truth", content: "", verses: [{ text: "When it is said to them: “Come to what Allah has revealed; come to the Messenger: They say: “Enough for us are the ways we found our fathers following.” What! Even though their fathers lacked knowledge and guidance?", reference: "Ch 5: V107-108" }, { text: "O you who believe! Guard your own souls: if you follow (right) guidance, no hurt can come to you from those who stray. The goal of you all is to Allah. It is He that will show you the truth of all that you do.", reference: "Ch 5: V107-108" }] },
      { subtitle: "11.2 Follow based on knowledge", content: "", verses: [{ text: "And pursue not that of which you have no knowledge; for every act of hearing, or of seeing or of (feeling in) the heart will be enquired into (on the Day of Reckoning).", reference: "Ch 17: V36" }] },
      { subtitle: "11.3 Cultures and traditions", content: "", verses: [{ text: "No! They say: “We found our fathers following a certain religion, and we do guide ourselves by their footsteps.”\n\nJust in the same way, whenever We sent a warner before you to any people, the wealthy ones among them said: “We found our fathers following a certain religion, and we will certainly follow in their footsteps.”\n\nHe said: “What! Even if I brought you better guidance than that which you found your fathers following?”\n\nThey said: “For us, we deny that you (prophets) are sent (on a mission at all).”", reference: "Ch 43: V22-24" }, { text: "When it is said to them: “Follow what Allah has revealed:” They say: “No! We shall follow the ways of our fathers.” What! Even though their fathers lacked wisdom and guidance?", reference: "Ch 2: V 170" }] },
      { subtitle: "11.4 Satan uses traditions to mislead", content: "", verses: [{ text: "When they are told to follow the (revelation) that Allah has sent down, they say: “No, we shall follow the ways that we found our fathers (following). “What! Even if it is Satan inviting them to the penalty of the (blazing) fire?", reference: "Ch 31: V21" }, { text: "When they do anything that is shameful, they say: “We found our fathers doing so”; and “(Allah) commanded us thus”: Say: “No, Allah never commands what is shameful: do you say of Allah what you do not know?”", reference: "Ch 7: V28" }] },
      { subtitle: "11.5 Every people will stand to account independently", content: "", verses: [{ text: "That was a people that have passed away. They shall reap the fruit of what they did, and you of what you do! Of their merits there is no question in your case.", reference: "Ch 2: V 141" }, { text: "He will say: “Enter you in the company of the people who passed away before you - men and jinns, - into the Fire.”Every time a new people enters, it curses its sister-people (that went before), until they follow each other, all into the fire. The last will say about the first: “Our Lord! It is these that misled us: so give them a double penalty in the Fire.” He will say: “Doubled for all”: but this you do not understand.", reference: "Ch 7: V38" }, { text: "Truly they found their fathers on the wrong path;\nSo they (too) made haste to follow! And truly before them, many of the ancients went astray;-\n\nBut We sent aforetime, among them, (messengers) to warn them;- Then see what was the end of those who were warned (but heeded not), except the sincere (and devoted) servants of Allah.", reference: "Ch 37: V69-74" }] },
      { subtitle: "11.6 Priestly commands can result in associating partners to Allah", content: "", verses: [{ text: "They take their priests and their rabbis and monks to be their lords besides Allah, and (they take as their lord) Christ the son of Mary; yet they were commanded to worship but one Allah. There is no god but He. Praise and Glory to Him: (far is He) from having the partners they associate (with Him).", reference: "Ch 9: V31" }] }
    ]
  },
  {
    id: "ch12", chapterNum: "12", title: "WHAT DOES ALLAH SAY ABOUT SUPERSTITIONS",
    sections: [
      { subtitle: "Introduction", content: "The following verses relate to various Arab superstitions as this group were the first recipients of the Quran. However, the general principles are still appropriate. In these examples special significance was associated with entrance into a home, movements of the moon, animals and their appearances etc. All such superstitions are falsely attributed to Allah and goes against the teachings of the Message of Allah.", verses: [] },
      { subtitle: "12.1 Superstitions are suggested by Satan", content: "", verses: [{ text: "“(Satan said) I will mislead them, and I will create in them false desires; I will order them to slit the ears of cattle, and to deface the (fair) nature created by Allah.” Whoever, forsaking Allah, takes Satan for a friend, has clearly suffered a great loss.", reference: "Ch 4: V 119." }] },
      { subtitle: "12.2 Superstitions are not from Allah", content: "", verses: [{ text: "It was not Allah who instituted (superstitions like those of) a slit-ear she- camel, or a she-camel let loose for free pasture, or idol sacrifices for twin-births in animals, or stallion-camels freed from work: it is blasphemers who invent a lie against Allah. But most of them lack wisdom.\nWhen it is said to them: “Come to what Allah has revealed; come to the Messenger: They say: “Enough for us are the ways we found our fathers following.” What! Even though their fathers lacked knowledge and guidance?", reference: "Ch 5: V106-107" }] },
      { subtitle: "12.3 Superstitions are lies attributed to Allah – a serious crime", content: "", verses: [{ text: "...of camels a pair, and oxen a pair; say, has He forbidden the two males, or the two females, or (the young) which the wombs of the two females enclose? Were you present when Allah ordered you such a thing? But who does more wrong than one who invents a lie against Allah, to lead astray men without knowledge? For Allah guides not people who do wrong.", reference: "Ch 6: V144" }] },
      { subtitle: "12.4 Fear Allah instead of following superstitions to be prosperous", content: "", verses: [{ text: "They ask you concerning the new moons. Say: They are but signs to mark fixed periods of time in (the affairs of) men, and for pilgrimage. It is no (special) virtue if you enter your houses from the back: it is virtue if you fear Allah. Enter houses through the proper doors: and fear Allah that you may prosper.", reference: "Ch 2: V 189" }] }
    ]
  },
  {
    id: "ch13", chapterNum: "13", title: "WHAT DOES ALLAH SAY ABOUT MUHAMMAD?",
    sections: [
      { subtitle: "13.1 Last of the Prophets", content: "", verses: [{ text: "Muhammad is not the father of any of your men, but (he is) the Messenger of Allah, and the Seal (Last) of the Prophets: and Allah has full knowledge of all things.", reference: "Ch 33: V40" }] },
      { subtitle: "13.2 A universal messenger", content: "", verses: [{ text: "We have sent you as a universal (messenger) to men, giving them glad tidings, and warning them (against sin), but most men understand not.", reference: "Ch 34: V28" }] },
      { subtitle: "13.3 A human like other humans", content: "", verses: [{ text: "Say: “I am but a man like yourselves, (but) the inspiration has come to me, that your God is one Allah: whoever expects to meet his Lord, let him do good actions, and, in the worship of his Lord, join no one as a partner.", reference: "Ch 18: V110" }] },
      { subtitle: "13.4 Received the light of revelation – the Quran", content: "", verses: [{ text: "And thus have We, by Our Command, sent inspiration to you: you did not know (before) what was Revelation, and what was Faith; but We have made the (Quran) a Light, with which We guide such of Our servants as We will; and verily you guide (men) to the Straight Way.", reference: "Ch 42: V 52" }] },
      { subtitle: "13.5 Did not have knowledge of the future", content: "", verses: [{ text: "Say: “I am not the first of the messengers, nor do I know what will be done with me or with you. I follow but that which is revealed to me by inspiration; I am but a warner open and clear.”", reference: "Ch 46: V9" }] },
      { subtitle: "13.6 Cannot change the Quran – only follows it as revealed", content: "", verses: [{ text: "But when Our clear signs are rehearsed unto them, those who rest not their hope on their meeting with Us, Say: “Bring us a Quran other than this, or change this,” Say: “It is not for me, of my own accord, to change it: I follow nothing but what is revealed unto me: if I were to disobey my Lord, I should myself fear the penalty of a Great Day (to come).”", reference: "Ch 10: V15" }] },
      { subtitle: "13.7 Has a beautiful pattern of conduct", content: "", verses: [{ text: "You have indeed in the Messenger of Allah an excellent example for any one whose hope is in Allah and the final Day, and who engages much in the Praise of Allah.", reference: "Ch 33: V21" }] },
      { subtitle: "13.8 Removed restrictions not sanctioned by Allah", content: "", verses: [{ text: "Those who follow the messenger, the untutored Prophet, whom they find mentioned in their own (scriptures), in the Torah and the Gospel;- for he commands them what is just and forbids them what is evil; he allows them as lawful what is good (and pure) and prohibits them from what is bad (and impure); he releases them from their heavy burdens and from the shackles that are upon them. So it is those who believe in him, honour him, help him, and follow the light which is sent down with him, it is they who will prosper.", reference: "Ch 7: V157" }] },
      { subtitle: "13.9 Did not have (secret) treasures (or knowledge)", content: "", verses: [{ text: "Say: “I tell you not that with me are the treasures of Allah, nor do I know what is hidden, nor do I tell you I am an angel. I only follow what is revealed to me.” Say: “Can the blind be held equal to the seeing?” Will you not then reflect?", reference: "Ch 6: V50" }] },
      { subtitle: "13.10 Exalted standard of character", content: "", verses: [{ text: "And you (O Muhammad) are of the noblest moral character.", reference: "Ch 68: V4" }] },
      { subtitle: "13.11 No more than a messenger", content: "", verses: [{ text: "Muhammad is no more than a messenger: messengers have passed away before him. If he died or were killed, will you then turn back on your heels? If any did turn back on his heels, not the least harm will he do to Allah; but Allah (on the other hand) will swiftly reward those who (serve Him) with gratitude.", reference: "Ch 3: V144" }] },
      { subtitle: "13.12 A mercy to all creation", content: "", verses: [{ text: "We sent you not, but as a Mercy for all creation.", reference: "Ch 21: V107" }] },
      { subtitle: "13.13 Complains that people had left the Quran", content: "", verses: [{ text: "Then the messenger (Muhammad) will say “O My Lord! Truly my people deserted this Quran.”", reference: "Ch 25: V30" }] }
    ]
  }
];
