export const bookData3 = [
  {
    id: "ch14", chapterNum: "14", title: "WHO ARE THE PROPHETS IN ISLAM?",
    sections: [
      { subtitle: "", content: "", verses: [{ text: "We have sent you (O Muhammad) revelation, as We sent it to Noah and the Messengers after him: we sent revelation to Abraham, Ismail, Isaac, Jacob and the Tribes, to Jesus, Job, Jonah, Aaron, and Solomon, and to David We gave the Psalms.\nOf some messengers We have already told you the story; of others We have not; and to Moses Allah spoke direct.", reference: "Ch 4: V 163-164" }] }
    ]
  },
  {
    id: "ch15", chapterNum: "15", title: "WHAT IS THE PURPOSE OF THE STORIES OF THE PROPHETS IN THE QURAN?",
    sections: [
      { subtitle: "", content: "", verses: [{ text: "All that We relate to you of the stories of the messengers, with it We make firm your heart: In them there comes to you the truth, as well as a warning and a reminder to those who believe.", reference: "Ch 11: V120" }] }
    ]
  },
  {
    id: "ch16", chapterNum: "16", title: "LESSONS FROM THE STORIES OF THE PROPHETS",
    sections: [
      { subtitle: "16.1 Similar message given to all Prophets", content: "", verses: [{ text: "For We certainly sent amongst every people a messenger, (with the Command) “Serve Allah, and stay away from Evil”. Of the people were some whom Allah guided, and some received the misguidance they deserved…", reference: "Ch 16: V36" }] },
      { subtitle: "16.2 Prophets and lessons of warning", content: "", verses: [] },
      { subtitle: "16.2.1 Nuh – Message delivered but ungratefully rejected", content: "", verses: [{ text: "“(Nuh said) And every time I have called to them, that You might forgive them, They have (only) put their fingers into their ears, covered themselves up with their garments, grown stubborn, and given themselves up to arrogance. “So I have called to them aloud;”Further I have spoken to them in public and in private ...", reference: "Ch 71: V7-9" }, { text: "But they rejected him (Nuh), and We delivered him, and those with him, in the Ark: but We drowned in the flood those who rejected Our signs. They were indeed a blind people!", reference: "Ch 7: V64" }] },
      { subtitle: "16.2.2 Hud and the Ad – Arrogant community destroyed", content: "", verses: [{ text: "Now the ‘Ad (people) behaved arrogantly through the land, against (all) truth and reason, and said: “Who can be more powerful than us?” What! Did they not see that Allah, who created them, is more powerful than them? But they continued to reject Our Signs!", reference: "Ch 41: V15" }, { text: "And the ‘Ad, They were destroyed by a furious wind, exceedingly violent.", reference: "Ch 69: V6" }] },
      { subtitle: "16.2.3 Salih and the Thamud – Materialism", content: "", verses: [{ text: "(Remember also) the ‘Ad and the Thamud (people): whose condition is clear to you from (the ruins) of their buildings: Satan made their actions seem good to them, and kept them back from the path, though they were gifted with intelligence and skill.", reference: "Ch 29: V38" }, { text: "He said: “Here is a she-camel: she has a right of watering, and you have a right of watering, (severally) on a Day appointed. “Touch her not with harm, lest the penalty of a great Day seize you.”\nBut they ham-strung her: then did they become full of regrets.", reference: "Ch 26: V155-157" }, { text: "But the Thamud, they were destroyed by a terrible storm of thunder and lightning!", reference: "Ch 69: V5" }] },
      { subtitle: "16.2.4 Lut & the people of Sodom & Gomorah – Immorality", content: "", verses: [{ text: "We also (sent) Lut: He said to his people: “Do you commit obscenity (homosexuality) such as no people in creation (ever) committed before you?\n“For you practise your lusts on men in preference to women: you are indeed a people transgressing.”", reference: "Ch 7: V80-81" }, { text: "We sent against them a violent tornado with showers of stones, (which destroyed them), except Lut’s household: them We saved by early Dawn, as a Grace from Us ...", reference: "Ch 54: V34-35" }] },
      { subtitle: "16.2.5 Shuaib & the people of Madyan – Economic exploitation", content: "", verses: [{ text: "To the Madyan people We sent their brother Shu’aib, he said: “O my people! Worship Allah; you have no other god but Him. Now has come unto you a clear (Sign) from your Lord! Give full measure and full weight, nor withhold from the people the things that are their due; and do no mischief on the earth after it has been set in order: that will be best for you, if you have Faith.", reference: "Ch 7: V85" }, { text: "But the earthquake took them unawares, and they lay prostrate in their homes before the morning!", reference: "Ch 7: V91" }] },
      { subtitle: "16.2.6 Moses & the Pharaoh – Political & Economic oppression", content: "", verses: [{ text: "Truly Pharaoh glorified himself in the earth and broke up its people into groups, weakening a small group among them: their sons he slew, but he kept alive their females: for he was indeed a maker of mischief.", reference: "Ch 28: V4" }, { text: "Then He (Pharaoh) collected (his men) and made an announcement, saying, “I am your Lord, Most High” but Allah did punish him, (and made an) example of him, in the Hereafter, as in this life.", reference: "Ch 79: V23-25" }, { text: "Like the ways of the people of Pharaoh and those before them: They treated as false the Signs of their Lord: so We destroyed them for their crimes, and We drowned the people of Pharaoh: for they were all oppressors and wrong-doers.", reference: "Ch 8: V54" }] },
      { subtitle: "16.3 Prophets and other lessons", content: "", verses: [] },
      { subtitle: "16.3.1 Yunus – Benefits of accepting the message", content: "", verses: [{ text: "Why was there not a single township (among those We warned), which believed, so its faith should have profited it,- except the people of Jonah? When they believed, We turned away from them the punishment of disgrace in this worldly life, and allowed them to enjoy (their life) for a while.", reference: "Ch 10: V98" }] },
      { subtitle: "16.3.2 Abraham – The use of reason", content: "", verses: [{ text: "Have you not thought of him who argued with Abraham about his Lord, because Allah had granted him power? Abraham said: “My Lord is He Who gives life and death.” He said: “I give life and death”. Said Abraham: “But it is Allah that causes the sun to rise from the east: do you then cause it to rise from the west?” Thus was he silenced who (in arrogance) rejected faith. Nor does Allah give guidance to a people unjust.", reference: "Ch 2: V 258" }, { text: "When Abraham said: “Show me, Lord, how You will raise the dead, “ He replied: “Have you no faith?” He said “Yes, but just to satisfy my heart.”…", reference: "Ch 2: V 260" }] },
      { subtitle: "16.3.3 David & Solomon - Just and wise leadership", content: "", verses: [{ text: "To Solomon We revealed the (right) understanding of the matter: to each (of them) We gave Judgment and Knowledge; it was Our power that made the hills and the birds celebrate Our praises, with David: it was We Who did (all these things).\nIt was We Who taught him the making of coats of mail for your benefit, to guard you from each other’s violence: will you then be grateful?", reference: "Ch 21: V79 - 80" }] },
      { subtitle: "16.3.4 Isa - Restored original teachings", content: "", verses: [{ text: "And in their footsteps We sent Jesus the son of Mary, confirming the Law that had come before him: We sent him the Gospel: therein was guidance and light, and confirmation of the Law that had come before him: a guidance and a warning to those who fear Allah.", reference: "Ch 5: V49" }, { text: "When Jesus came with Clear Signs, he said: “Now have I come to you with Wisdom, and in order to make clear to you some of the (points) on which you differ: therefore fear Allah and obey me.", reference: "Ch 43: V63" }, { text: "And behold! Allah will say: “O Jesus the son of Mary! Did you say unto men, worship me and my mother as gods instead of Allah’?” He will say: “Glory to You! Never could I say what I had no right (to say). Had I said such a thing, You would indeed have known it. You know what is in my heart; I know not what is in Yours. For You know in full all that is hidden.", reference: "Ch 5: V119" }] }
    ]
  },
  {
    id: "ch17", chapterNum: "17", title: "WHAT DOES IT MEAN TO BE A MUSLIM?",
    sections: [
      { subtitle: "17.1 To be leaders and good examples to humanity", content: "", verses: [{ text: "You are the best of peoples, evolved for mankind, enjoining what is right, forbidding what is wrong, and believing in Allah. If only the People of the Book had faith, it was best for them: among them are some who have faith, but most of them are transgressors.", reference: "Ch 3: V110" }] },
      { subtitle: "17.2 To call oneself a Muslim and nothing else", content: "", verses: [{ text: "... He (Allah) has chosen you, and has imposed no difficulties on you in religion; it is the way of your father Abraham. It is He Who has named you Muslims, both before and in this (Revelation) ...", reference: "Ch 22: V 78" }] },
      { subtitle: "17.3 Uphold unity", content: "", verses: [{ text: "As for those who divide their religion and break up into sects, you (O Muhammad) have no part in them in the least: their affair is with Allah: He will in the end tell them the truth of all that they did.", reference: "Ch 6: V159" }] }
    ]
  },
  {
    id: "ch18", chapterNum: "18", title: "WHAT ARE THE BASIC ETIQUETTES OF A MUSLIM",
    sections: [
      { subtitle: "18.1 Eating: be grateful and do not waste", content: "", verses: [{ text: "So eat of the sustenance which Allah has provided for you, lawful and good; and be grateful for the favours of Allah, if it is He Whom you serve.", reference: "Ch 16: V114" }, { text: "... eat and drink: but waste not by excess, for Allah does not love the wasters.", reference: "Ch 7: V31" }] },
      { subtitle: "18.2 Greeting: be courteous", content: "", verses: [{ text: "When a (courteous) greeting is offered to you, meet it with a greeting still more courteous, or (at least) of equal courtesy. Allah takes careful account of all things.", reference: "Ch 4: V 86" }] },
      { subtitle: "18.3 Speech: be clear and just", content: "", verses: [{ text: "O you who believe! Fear Allah, and (always) speak clearly and justly.", reference: "Ch 33: V70" }, { text: "... and when the ignorant address them, they say, “Peace!”", reference: "Ch 25: V63" }] },
      { subtitle: "18.4 Walking & talking: be humble", content: "", verses: [{ text: "And the servants of (Allah) Most Gracious are those who walk on the earth in humility...", reference: "Ch 25: V63" }, { text: "And be moderate in your pace, and lower your voice; for the harshest of sounds without doubt is the braying of the donkey.”", reference: "Ch 31: V19" }] },
      { subtitle: "18.5 Visiting: ask permission and greet", content: "", verses: [{ text: "O you who believe! Enter not houses other than your own, until you have asked permission and greeted those in them: that is best for you, in order that you may be mindful.\nIf you find no one in the house, enter not until permission is given to you: if you are asked to go back, go back: that makes for greater purity for yourselves: and Allah knows well all that you do.", reference: "Ch 24: V 27 - 28" }] },
      { subtitle: "18.6 Invitation: don’t be too early or late", content: "", verses: [{ text: "O you who believe! Enter not the Prophet’s houses,- until permission is given you,- for a meal, (and then) not (so early as) to wait for its preparation: but when you are invited, enter; and when you have taken your meal, leave, without seeking familiar talk. ..", reference: "Ch 33: V53" }] },
      { subtitle: "18.7 Dress: best clothing is righteous character", content: "", verses: [{ text: "O you Children of Adam! We have bestowed clothing upon you to cover your shame, as well as to be a beautification to you. But the clothing of righteousness, - that is the best. Such are among the Signs of Allah, that they may be mindful!", reference: "Ch 7: V26" }] },
      { subtitle: "18.8 Relations between men and women: modesty", content: "", verses: [{ text: "Say to the believing men that they should lower their gaze and guard their modesty: that will make for greater purity for them… and (also) say to the believing women that they should lower their gaze and guard their modesty", reference: "Ch 24: V 30-31" }] }
    ]
  },
  {
    id: "ch19", chapterNum: "19", title: "WHAT ARE THE CHARACTERISTICS OF A MUSLIM?",
    sections: [
      { subtitle: "19.1 Submission to Allah", content: "", verses: [{ text: "Whoever submits his whole self to Allah, and is a doer of good, has grasped indeed the most trustworthy hand-hold: and with Allah rests the end and decision of (all) affairs.", reference: "Ch 31: V22" }] },
      { subtitle: "19.2 Beneficial to others", content: "", verses: [{ text: "... do good- to parents, relatives, orphans, those in need, neighbours who are near, neighbours who are strangers, the companion by your side, the wayfarer (you meet), and those under your custody ...", reference: "Ch 4: V 36" }] },
      { subtitle: "19.3 Humble", content: "", verses: [{ text: "And swell not your cheek (for pride) at men, nor walk arrogantly through the earth; for Allah loves not any arrogant boaster.", reference: "Ch 31: V18" }] },
      { subtitle: "19.4 Forgiving", content: "", verses: [{ text: "The recompense for an injury is an injury equal thereto (in degree): but if a person forgives and makes reconciliation, his reward is due from Allah: for (Allah) loves not those who do wrong.", reference: "Ch 42: V 40" }] },
      { subtitle: "19.5 Grateful", content: "", verses: [{ text: "We bestowed (in the past) wisdom on Luqman: “Show gratitude to Allah.” Any who is (so) grateful does so to the profit of his own soul: but if any is ungrateful, verily Allah is free of all wants, worthy of all praise.", reference: "Ch 31: V12" }, { text: "Then do you remember Me (Allah); I will remember you. Be grateful to Me, and reject not Faith.", reference: "Ch 2: V 152" }] },
      { subtitle: "19.6 Know that the life of this world is a test", content: "", verses: [{ text: "Nor strain your eyes in longing for the things We have given for enjoyment to parties of them, the splendour of the life of this world, through which We test them: but the provision of thy Lord is better and more enduring.", reference: "Ch 20: V131" }, { text: "What is the life of this world but play and amusement? But best is the home in the hereafter, for those who are righteous. Will ye not then understand?", reference: "Ch 6: V 32" }] },
      { subtitle: "19.7 Just", content: "", verses: [{ text: "O you who believe! Stand out firmly for justice, as witnesses to Allah, even as against yourselves, or your parents, or your relatives, and whether it is (against) rich or poor: for Allah can best protect both. Follow not the desires (of your hearts), lest you swerve, and if you distort (justice) or decline to do justice, verily Allah is well-acquainted with all that you do.", reference: "Ch 4: V 135" }] },
      { subtitle: "19.8 Fulfil contracts", content: "", verses: [{ text: "O you who believe! Fulfil all contracts...", reference: "Ch 5: V1" }, { text: "(Believers are) those who faithfully observe their trusts and their covenants;", reference: "Ch 23: V8" }] },
      { subtitle: "19.9 Choose good company", content: "", verses: [{ text: "O you who believe! Fear Allah and be with those who are true (in word and deed).", reference: "Ch 9: V119" }] },
      { subtitle: "19.10 Avoid vain talk, futility and false evidence", content: "", verses: [{ text: "(Believers are those) who avoid vain talk;", reference: "Ch 23: V3" }, { text: "(Believers are) those who do not give false evidence and if they pass by futility, they pass by it with honourable (avoidance).", reference: "Ch 25: V72" }] },
      { subtitle: "19.11 Charitable", content: "", verses: [{ text: "... spend of your substance, out of love for Him, for your relatives, for orphans, for the needy, for the traveller, for those who ask, and for the ransom of slaves;", reference: "Ch 2: V 177" }] },
      { subtitle: "19.12 Balance in spending", content: "", verses: [{ text: "Those who, when they spend, are not extravagant and not stingy, but hold a just (balance) between those (extremes).", reference: "Ch 25: V67" }, { text: "But waste not (your wealth) in the manner of a spendthrift.\nVerily spendthrifts are brothers of Satan; and Satan is to his Lord ungrateful...", reference: "Ch 17: V26 - 27" }] },
      { subtitle: "19.13 Respectful and polite", content: "", verses: [{ text: "Say to My servants that they should (only) say those things that are best: for Satan does cause divisions among them: for Satan is to man an open enemy.", reference: "Ch 17: V53" }, { text: "O you who believe! Let not some men among you laugh at others: it may be that the (latter) are better than the (former): nor let some women laugh at others: it may be that the (latter) are better than the (former): nor defame nor be sarcastic to each other, nor call each other by (offensive) nicknames: ill-seeming is a name implying wickedness, (to be used of one) after he has believed: and those who do not turn away (from this) are (indeed) doing wrong.", reference: "Ch 49: V11" }] },
      { subtitle: "19.14 Establish peace", content: "", verses: [{ text: "The believers are but a single Brotherhood: so make peace and reconciliation between your two (contending) brothers; and fear Allah, that you may receive mercy.", reference: "Ch 49: V10" }] },
      { subtitle: "19.15 Avoid suspicion", content: "", verses: [{ text: "O you who believe! Avoid suspicion as much (as possible): for suspicion in some cases is a sin: and spy not on each other nor speak ill behind their backs. Would any of you like to eat the flesh of his dead brother? No, you would hate it...But fear Allah, for Allah is Oft-Returning, Most Merciful.", reference: "Ch 49: V12" }] },
      { subtitle: "19.16 Control their anger", content: "", verses: [{ text: "(Believers are those) who restrain anger, and forgive (all) men; for Allah loves those who do good.", reference: "Ch 3: V134" }, { text: "... when they are angry even then forgive;", reference: "Ch 42: V 37" }] },
      { subtitle: "19.17 Practice what they preach", content: "", verses: [{ text: "O you who believe! Why say you that which you do not (practice)?Most hateful is it in the sight of Allah that you say that which you do not.", reference: "Ch 61: V2 - 3" }] },
      { subtitle: "19.18 Assist in good causes and not bad ones", content: "", verses: [{ text: "Whoever recommends and helps a good cause becomes a partner therein: and whoever recommends and helps an evil cause, shares in its burden: and Allah has power over all things.", reference: "Ch 4: V 85" }] },
      { subtitle: "19.19 Spend time usefully", content: "", verses: [{ text: "By Time,\nVerily Man is in loss,\nExcept such as have faith, and do righteous actions, and (join together) in the mutual teaching of Truth, and of Patience and Constancy.", reference: "Ch 103: V1 - 3" }] },
      { subtitle: "19.20 Firm and patient", content: "", verses: [{ text: "...be firm and patient, in pain (or suffering) and adversity, and throughout all periods of panic. Such are the people of truth, the Allah-fearing.", reference: "Ch 2: V 177" }] }
    ]
  }
];
