export const bookData1 = [
  {
    id: "front-matter", chapterNum: "0", title: "INTRODUCTION & FOREWORD",
    sections: [
      { subtitle: "Publication Info", content: "Published by QSG Publications\nPO Box 14576\nLaudium\n0037\nSouth Africa\nemail: contact.pathwaytolight@gmail.com\nwww.alasr.co.za\nFirst Edition: 2011 CE / 1432 AH\nISBN: 978-0-620-50334-1", verses: [{ text: "... We have made the (Qur’an) a Light, wherewith We guide ...", reference: "Chapter 42: Verse 52" }] },
      { subtitle: "NOTES", content: "The translation used\nThe translation of verses from the Quran used in this book is by Abdullah Yusuf Ali as it is the most widely available and generally well accepted. However we have edited some of the translation to make it more reader friendly using simple English.\nPersonal pronouns We, He and I for God\nGod (Allah) is a Supreme Being and cannot be defined. Thus personal pronouns are used interchangeable when referring to God (Allah). Furthermore, the usage of “We” when referring to God (Allah) is in the sense of the majestic plural as would be done for kings. However it does not mean plurality of gods as the Quran is clear that “He (Allah) is the One and Only”.\nReferencing\nThe numbering of the verses follows the same translation and is usually in the convention of Sura (chapter) and Ayat (verse). An example is Ch 2: V 177 which refers to Sura (chapter) 2 and Ayat (verse) 177. This is sometimes written in Roman numerals e.g. chapter as II. Note: this book is aimed at being quick guide and we strongly urge the reader to refer back to the Quran for all references.\nRoman numerals simplified: I = 1, V= 5, X = 10, L=50, C=100. When alphabets occur before the largest value then you need to subtract and if they occur after you need to add. An example is XLII – refers to chapter 42 (L-X+II = 50-10+2).\nExpression of respect and honour\nIn order to express respect and honour, the following terms should be mentioned at the time of reading the terms Allah or any of His messengers:\nAllah – Glory be to Allah (God), the Most High.\nMessengers (e.g Moses, Jesus, Muhammad etc.) – Peace and blessings upon him (PBUH) or them.", verses: [] },
      { subtitle: "FOREWORD", content: "With the Name of God, The Compassionate, The Merciful\n\nThe authors of “Pathway to Light” need to be commended for this production. At a time when time has become such a precious commodity, this resource which succinctly conveys the essence of Islam will very quickly clear any misconceptions that non-muslims have about our faith. “Pathway to Light” is written in a simple intelligible way. It is neither esoteric nor pedantic. A reading will convey to the uninitiated the rich tapestry of Islam. Besides making compelling reading, hopefully it will stimulate the interest of the reader. “Pathway to Light” in many ways could be regarded as a quick overview of the Quran.\n\nFor the Muslim, “Pathway to Light” summarises beautifully the tenets of faith. It does not pretend to be exhaustive and as the title suggests it is a means to an end …indeed a pathway. It is not fortuitous that the first ayah to be revealed is Iqra. This noble habit has sadly been forsaken. It is indeed a sad indictment on our community that many of us have a limited understanding of our faith and its finest exemplar, our beloved Prophet Mohammed (PBUH).It is my prayer that “Pathway to Light” will rekindle our passion and need I say obligation to pursue knowledge relentlessly.\n\nI recommend very strongly that institutions like the Muslim Schools should make “Pathway to Light” compulsory reading for their learners.\n\nEdris Khamissa\nConsultant in Education and Human Development\nDurban - South Africa\nwww.edriskhamissa.com\nMobile +27828251991", verses: [] },
      { subtitle: "INTRODUCTION", content: "Pathway to light\nThe important things in life are often straight forward and simple – such is the case with the word of Allah – leading humanity from the depths of darkness to light. This book is aimed at putting forward the truth of Islam from its pure source in simple language, for everyone to easily follow the pathway to light.\n\nThe beginning; not the end\nIt is important to note that this book is a brief introduction and as such is not exhaustive. The reader is urged to confirm the contents of the material and gain a more complete understanding of topics listed in this book, by referring back to the Quran.\n\nGod (Allah) answers\nThe basic principles and practices of Islam are herein presented in a question and answer format. The answers are given with verses directly from the Quran – the final, perfect and unchanged word of God (Allah) – without further commentaries or interpretations. This approach has been used because the Quran is the common factor accepted among all Muslims the world over.\n\nThe Quran and Muhammad (PBUH)\nThe Prophet Muhammad (PBUH) was the final messenger who brought humanity out of darkness into light with the final revelation – the Quran. It re-established the direct link between the Creator and the created. It was the revelation of the Quran which was read, understood and applied by the Prophet (PBUH) and his companions that changed society to one of justice, mercy and righteous behaviour.\n\nQuick reference guide\nThis book is aimed at being a quick reference guide. Its short summarised topics will quickly familiarise the reader with the remarkable message of the Creator. The contents page is expanded to allow for a quick reference to topics of interest. For ease of use, sections have captions that highlight the important message of the verses listed.\n\nWe need solutions\nThe world in the 21st century has advanced materially but not morally. It is sad that the greatest blessing to humanity has been set aside leaving mankind in spiritual darkness. The Quran has revitalised humanity before and is capable of repeating it. What is required is to read, understand and apply its teachings. Are we going to open our hearts to this pathway to light from our Creator?\n\nOur prayer\nWe pray that humanity will open their hearts and minds to the Book of Allah and use it as a medium to gain closeness to Him and benefit society by applying its teachings. All Glory belongs to Allah, the Incomparable, the Absolute.", verses: [] }
    ]
  },
  {
    id: "ch1", chapterNum: "1", title: "WHO IS GOD (ALLAH)?",
    sections: [
      { subtitle: "1.1 The word ‘Allah’", content: "This is the proper name of God Almighty, the Creator of everything that exists, the one and the only, as mentioned in the Arabic Quran. This name has no gender and no plural; it is unique and is not shared by any other being.", verses: [{ text: "Say: He is Allah, the One and Only;\nAllah is He on whom all depend;\nHe has no children and is not anyone’s child;\nand there is none like Him.", reference: "Ch 112: V1-4" }] },
      { subtitle: "1.2 Supreme Being", content: "No being can see or fully understand Allah and we can’t limit Allah to what we can only understand.", verses: [{ text: "That is Allah, your Lord! There is no god but He, the Creator of all things: then worship you Him: and He has power to dispose of all affairs.\nNo vision can grasp Him, but His grasp is over all vision: He is above all comprehension, yet is aware of the finest details.", reference: "Ch 6: V102-103" }] },
      { subtitle: "1.3 Names or Attributes of Allah", content: "We are given many Names or Attributes of Allah in the Quran to assist us understand the qualities of Allah.", verses: [{ text: "Allah is He, than Whom there is no other god;- Who knows (all things) both secret and open; He, Most Gracious, Most Merciful.\nAllah is He, than Whom there is no other god;-\nThe King, The Holy One, The Source of Peace (and Perfection), The Giver of Faith, The Preserver of Safety,\nThe Almighty, The Irresistible, The Supreme: Glory to Allah! (High is He) above the partners they attribute to Him.\nHe is Allah, The Creator, The Maker Who shapes all forms and appearances. To Him belong the Most Beautiful Names: whatever is in the heavens and on earth, declares His Praises and Glory: and He is The Mighty, The Wise.", reference: "Ch 59: V22-24" }] },
      { subtitle: "", content: "There are numerous other qualities that describe The One and Only Allah throughout the Quran.", verses: [] },
      { subtitle: "1.4 Warning against joining partners to Allah", content: "Attributing anything else to what is due to Allah can be setting up partners with Allah. Whether it be human, things in nature (e.g. the sun), idols and even a person’s own desire. This is stated in the Quran as being the worst evil and an unforgivable sin if one does not repent and amend.", verses: [{ text: "Allah forgives not that partners should be set up with Him; but He forgives anything else, to whom He pleases; whoever sets up partners with Allah has indeed invented a terrible sin.", reference: "Ch 4: V 48" }] }
    ]
  },
  {
    id: "ch2", chapterNum: "2", title: "WHAT IS THE PURPOSE OF OUR EXISTENCE?",
    sections: [
      { subtitle: "2.1 Serving Allah", content: "", verses: [{ text: "I have only created Jinns and men, that they may serve Me (Allah).", reference: "Ch 51: V56" }] },
      { subtitle: "2.2 Doing what is right and avoiding what is wrong", content: "", verses: [{ text: "By the Soul, and He Who perfected it;\nAnd inspired it with knowledge of what is wrong and what is right;-\nTruly he succeeds that purifies it,\nAnd he fails that corrupts it!", reference: "Ch 91: V7-10" }] },
      { subtitle: "2.3 A test of actions", content: "", verses: [{ text: "The One (Allah) who created death and life, so that He may test which of you is best in actions: and He is The Almighty, The All-Forgiving;-", reference: "Ch 67: V2" }, { text: "That which is on earth We have made but as a glittering show for the earth, in order that We may test them - as to which of them are best in conduct.", reference: "Ch 18: V7" }] },
      { subtitle: "2.4 To be representative / care-taker of the world", content: "", verses: [{ text: "Behold, your Lord said to the angels: “I will create a representative on earth.” They said: “Will You place therein one who will make mischief therein and shed blood while we do celebrate Your praises and glorify Your Holy (Name)?” He said: “I know what you know not.”", reference: "Ch 2: V 30" }] },
      { subtitle: "", content: "The main purpose of life is to serve Allah. However, Allah is free of all wants, so serving Allah means to serve His creation. Thus our purpose in this world is to benefit humanity. We need to establish balance and equilibrium in society and remove all forms of imbalances. We need to be aware that what Allah has given us (our lives, time, wealth etc.) is a test of our conduct for which we are accountable.", verses: [] }
    ]
  },
  {
    id: "ch3", chapterNum: "3", title: "WHERE DO WE FIND ALLAH’S GUIDANCE?",
    sections: [
      { subtitle: "3.1 In the Quran", content: "", verses: [{ text: "This is the Book (the Quran); in it is guidance sure, without doubt, to those who are conscious of Allah.", reference: "Ch 2: V 2" }] },
      { subtitle: "3.2 The guidance of Allah is the only guidance", content: "", verses: [{ text: "... Say: “The Guidance of Allah,-that is the (only) Guidance.”", reference: "Ch 2: V 120" }] }
    ]
  },
  {
    id: "ch4", chapterNum: "4", title: "HOW DOES THE WILL OF ALLAH WORK?",
    sections: [
      { subtitle: "4.1 Guidance and straying are according to the Will of Allah", content: "", verses: [{ text: "We never sent a messenger except (to teach) in the language of his (own) people, in order to make (things) clear to them. Now Allah leaves straying those whom He pleases and guides whom He pleases: and He is Exalted in Power, Full of Wisdom.", reference: "Ch 14: V4" }] },
      { subtitle: "", content: "The verses in 6.2 to 6.7. explains the above verse.", verses: [] },
      { subtitle: "4.2 Allah’s will is to guide those who seek His guidance", content: "", verses: [{ text: "And Allah does advance in guidance those who seek guidance ...", reference: "Ch 19: V76" }] },
      { subtitle: "4.3 Allah’s will is to guide those who turn to Him", content: "", verses: [{ text: "...Say: “Truly Allah leaves, to stray, whom He will; but He guides to Himself those who turn to Him.", reference: "Ch 13: V27" }] },
      { subtitle: "4.4 Allah’s will is to leave astray those who do wrong", content: "", verses: [{ text: "Allah will establish in strength those who believe ...but Allah will leave, to stray, those who do wrong: Allah does what He wills.", reference: "Ch 14: V27" }] },
      { subtitle: "4.5 Allah causes not to stray except those who forsake His path", content: "", verses: [{ text: "…but He causes not to stray, except those who forsake (the path),-", reference: "Ch 2: V 26" }] },
      { subtitle: "4.6 Allah helps those who try to change", content: "", verses: [{ text: "... Verily never will Allah change the condition of a people until they change themselves, but when Allah wills a people’s punishment, there can be no turning it back, nor will they find, besides Him, any to protect.", reference: "Ch 13: V11" }] },
      { subtitle: "4.7 Allah’s way of dealing with humankind is consistent", content: "", verses: [{ text: "(Such has been) the way of Allah which has been in force in the past: and never will you find any change in the way of Allah.", reference: "Ch 48: V23" }] }
    ]
  },
  {
    id: "ch5", chapterNum: "5", title: "WHAT IS THE BASIC RECIPE FOR SALVATION?",
    sections: [
      { subtitle: "5.1 To believe and do righteous actions", content: "", verses: [{ text: "For those who believe and do righteous actions, will be Gardens; beneath which rivers flow: that is the great salvation, (the fulfilment of all desires).", reference: "Ch 85: V11" }] }
    ]
  },
  {
    id: "ch6", chapterNum: "6", title: "WHAT ARE THE BELIEFS OF ISLAM?",
    sections: [
      { subtitle: "Introduction", content: "The articles of belief are listed in the verse below and described in further detail thereafter.", verses: [{ text: "O you who believe! Believe in Allah and His Messenger, and the scripture which He has sent to His Messenger and the scripture which He sent to those before (him). Any who denies Allah, His angels, His Books, His Messengers and the Day of Judgment, has gone far, far astray.", reference: "Ch 4: V 136" }] },
      { subtitle: "6.1 Allah", content: "Refer to 1.1 – 1.4", verses: [] },
      { subtitle: "6.2 Angels", content: "The angels, unlike us humans have no choice in their actions. They worship and serve Allah at all times.", verses: [] },
      { subtitle: "6.2.1 They do only what God commands them", content: "", verses: [{ text: "(The angels say :) “We descend not but by command of your Lord: to Him belongs what is before us and what is behind us, and what is between: and your Lord never does forget.", reference: "Ch 19: V64" }] },
      { subtitle: "6.2.2 They bring revelation", content: "", verses: [{ text: "He does send down His angels with inspiration of His Command, to such of His servants as He pleases (saying): “Warn (mankind) that there is no god but I: so do your duty unto Me.”", reference: "Ch 16: V2" }] },
      { subtitle: "6.2.3 They bring destruction by God’s command", content: "", verses: [{ text: "We send not the angels down except for just cause: if they came (to the ungodly), behold! No respite would they have!", reference: "Ch 15: V8" }] },
      { subtitle: "6.3 Books", content: "Allah sent revelation from time to time to His messengers for their people’s guidance. Previous scriptures were changed and the Quran is the final scripture.", verses: [{ text: "It is He Who sent down to you (step by step), in truth, the Book, confirming what went before it; and He sent down the Law (of Moses) and the Gospel (of Jesus) before this, as a guide to mankind, and He sent down the criterion (the Quran – a judgment between right and wrong).", reference: "Ch 3: V3" }, { text: "O People of the Book! There has come to you Our Messenger, revealing to you much that you used to hide in the Book, and passing over much (that is now unnecessary): There has come to you from Allah a (new) light and a clear Book.", reference: "Ch 5: V16-17" }] },
      { subtitle: "6.4 Messengers", content: "Messengers were humans sent by Allah from time to time to guide mankind to Allah and His message.", verses: [] },
      { subtitle: "6.4.1 Messengers were all humans", content: "", verses: [{ text: "And the messengers whom We sent before thee were all (men) who ate food and walked through the streets ...", reference: "Ch 25: V 20" }] },
      { subtitle: "6.4.2 They act by His command", content: "", verses: [{ text: "They (the Messengers) speak not before He speaks, and they act (in all things) by His Command.", reference: "Ch 21: V27" }, { text: "We sent not an apostle, but to be obeyed, In accordance with the will of Allah…", reference: "Ch 4: V 64" }] },
      { subtitle: "6.4.3 All the messengers to be accepted", content: "", verses: [{ text: "Say you: “We believe in Allah, and the revelation given to us, and to Abraham, Ismail, Isaac, Jacob, and the Tribes, and that given to Moses and Jesus, and that given to (all) prophets from their Lord: We make no difference between one and another of them: And we bow to Allah (in Islam).”", reference: "Ch 2: V 136" }] },
      { subtitle: "", content: "• All of them had the same basic message as Muhammad (PBUH) i.e. to believe and worship one Allah alone.", verses: [{ text: "Not a messenger did We send before you without this inspiration sent by Us to him: that there is no god but I; therefore worship and serve Me.", reference: "Ch 21: V25" }] },
      { subtitle: "6.5 Day of Judgement", content: "Life in this world is temporary. When we die the only thing that matters is the actions we have done. Everyone is accountable for his or her own actions on the Day of Judgement.", verses: [{ text: "Allah! There is no god but He: certainly He will gather you together on the Day of Judgment, about which there is no doubt. And whose word can be truer than Allah’s?", reference: "Ch 4: V 87" }, { text: "And the Book (of deeds) will be placed (before and you will see the sinful in great terror because of what is (recorded). They will say, “Ah! Curse to us! What a Book is this! It leaves out nothing small or great, but takes account thereof!” They will find all that they did placed before them: and none will your Lord treat with injustice.", reference: "Ch 18 : V49" }, { text: "And to every soul will be paid in full (the fruit) of its actions; and (Allah) knows best all that they do.", reference: "Ch 39: V70" }, { text: "...and no soul earns (evil) but against itself: no bearer of burdens can bear the burden of another. Your goal in the end is towards Allah: He will tell you the truth of the things wherein you disagreed.”", reference: "Ch 6: V164" }] }
    ]
  },
  {
    id: "ch7", chapterNum: "7", title: "Death and the Hereafter",
    sections: [
      { subtitle: "7.1 Everyone will die", content: "", verses: [{ text: "Every soul shall have a taste of death: and only on the Day of Judgment shall you be paid your full recompense. Only He who is saved far from the Fire and admitted to the Garden will have attained the object (of Life): for the life of this world is but goods and chattels of deception.", reference: "Ch 3: v185" }] },
      { subtitle: "7.2 Cannot come back to earth when dead", content: "", verses: [{ text: "(In falsehood will they be) until, when death comes to one of them, He says: “O My Lord! Send me back (to life),- “In order that I may work righteousness In the things I neglected.” - “By no means! it is but a word he says.”- Before them is a Partition till the Day they are raised up.", reference: "Ch 23 : v99,100" }] },
      { subtitle: "7.3 The world will end a new world will begin", content: "", verses: [{ text: "On the Day when the heavens will be in dreadful commotion and the mountains will fly hither and thither. Then curse that Day to those that treat (Truth) as Falsehood;-", reference: "Ch 52: 9-11" }, { text: "One day the earth will be changed to a different earth, and so will be the heavens and (men) will be marshalled forth, before Allah, the One, the Irresistible;", reference: "Ch 14: V 48" }] },
      { subtitle: "", content: "After Judgment we will be sent to either Heaven or Hell.", verses: [] },
      { subtitle: "7.4 Righteous will be rewarded with the garden", content: "", verses: [{ text: "And we shall remove from their hearts any lurking sense of injury;- beneath them will be rivers flowing;- and They shall say: “Praise be to Allah, who hath guided us to This (felicity): never could we have found guidance, had it not been for the guidance of Allah. Indeed it was the truth that the apostles of Our Lord brought unto us.” and they shall hear the cry: “Behold! The Garden before you! you have been made its inheritors, for your deeds (of righteousness).”", reference: "Ch 7 : v43" }, { text: "They will say: “Praise be to Allah, who has truly fulfilled His promise to us, and has given us (this) land in heritage: we can dwell in the Garden as we will: How excellent a reward for those who work (righteousness)!”", reference: "Ch 39: V74" }, { text: "Now no person knows what delights of the eye are kept hidden (in reserve) for them - as a reward for their (good) actions.", reference: "Ch 32: V17" }, { text: "They shall have all that they wish for, in the presence of their Lord: such is the reward of those who do good.", reference: "Ch 39: V34" }] },
      { subtitle: "7.5 Righteous will be joined to their families", content: "", verses: [{ text: "And those who believe and whose families follow them In Faith,- to them shall we join their families: nor shall we deprive them (of the fruit) of any of their works: (yet) is each individual in pledge for his deeds.", reference: "Ch 52 : v21" }] },
      { subtitle: "7.6 Unrighteous will be punished in the Fire", content: "", verses: [{ text: "Truly Hell is as a place of ambush, for the transgressors a place of destination: They will dwell therein for ages. Nothing cool shall They taste therein, nor any drink, save a boiling fluid and a fluid, dark, murky, intensely cold, a fitting recompense (for them).", reference: "Ch 78 : V21 - 26" }, { text: "...But those who respond not to Him, even if they had all that is in the heavens and on earth, and as much more, (in vain) would they offer it for ransom. For them will the reckoning be terrible: their home will be Hell, what a bed of misery!", reference: "Ch 13: V18" }, { text: "Into Hell? They will burn therein, an evil place to stay!", reference: "Ch 14: V29" }] }
    ]
  }
];
